# Set home folder
# Use $HOME for portability
DBX_CONTAINER_HOME_PREFIX="$HOME/distroboxes"

# Force Distrobox to start inside defined work directory
DBX_SKIP_WORKDIR="1"

# Explicitly use Podman
DBX_CONTAINER_MANAGER="podman"

# Prevent Distrobox from checking for updates when entering container
# Idea is to speed up startup times
DBX_CONTAINER_ALWAYS_PULL="0"
